# Site settings
title: Juan | Data Scientist
description: Portfolio specializing in Risk Analysis, Machine Learning, and Statistical Analytics.
baseurl: ""
url: "https://juanhv24.github.io"

# User info
github_username: juanhv24
linkedin_username: juan-hernandez-vargas 
email: juandanihv@gmail.com

# Build settings
theme: jekyll-theme-minimal
markdown: kramdown
